version: '3.8'
services:
  track:
    image: track:latest
    container_name: track
    restart: always
  db:
    container_name: pg_container
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
