import { App } from './app';
import { Container } from 'inversify';
import { LoggerService } from './logger/logger.service';
import { ConfigService } from './config/config.service';
import { PrismaService } from './database/prisma.service';
import { IConfigService } from './config/config.service.interface';
import { IPrismaService } from './database/prisma.interface';
import { ILoggerService } from './logger/logger.interface';
import { ITrackRepository } from './tracker/track.repository.interface';
import { ITrackService } from './tracker/tracker.service.interface';
import { TrackRepository } from './tracker/track.repository';
import { TrackService } from './tracker/tracker.service';
import { IUserRepository } from './users/user.repository.interface';
import { UserRepository } from './users/user.repository';
import { IUserService } from './users/user.service.interface';
import { UserService } from './users/user.service';
import { TYPES } from './types';
import { IDeliverTrackService } from './deliver/deliver.track.service.interface';
import { DeliverTrackService } from './deliver/deliver.track.service';
import { IDeliverRepository } from './deliver/deliver.repository.interface';
import { DeliverRepository } from './deliver/deliver.repository';
import { IBotTracker } from './telegram/telegram.interface';
import { ITelegramMessageService } from './telegram/services/telegram.message.service.interface';
import { TelegramMessageService } from './telegram/services/telegram.message.service';
import { BotTracker } from './telegram/telegram';
import { FavoriteService } from './telegram/services/telegram.favorite.service';
import { BanService } from './telegram/services/telegram.ban.service';
import { IBanService } from './telegram/services/telegram.ban.service.interface';
import { IFavoriteService } from './telegram/services/telegram.favorite.service.interface';

const appContainer = new Container();
appContainer.bind<ILoggerService>(TYPES.ILoggerService).to(LoggerService).inSingletonScope();
appContainer.bind<IConfigService>(TYPES.IConfigService).to(ConfigService).inSingletonScope();
appContainer.bind<IPrismaService>(TYPES.IPrismaService).to(PrismaService).inSingletonScope();
appContainer.bind<ITrackRepository>(TYPES.ITrackRepository).to(TrackRepository);
appContainer.bind<ITrackService>(TYPES.ITrackService).to(TrackService);
appContainer.bind<IUserRepository>(TYPES.IUserRepository).to(UserRepository);
appContainer.bind<IDeliverRepository>(TYPES.IDeliverRepository).to(DeliverRepository);
appContainer.bind<IUserService>(TYPES.IUserService).to(UserService);
appContainer.bind<IBotTracker>(TYPES.IBotTracker).to(BotTracker);
appContainer.bind<IDeliverTrackService>(TYPES.IDeliverTrackService).to(DeliverTrackService);
appContainer.bind<IBanService>(TYPES.IDeliverTrackService).to(BanService);
appContainer.bind<IFavoriteService>(TYPES.IDeliverTrackService).to(FavoriteService);
appContainer
	.bind<ITelegramMessageService>(TYPES.ITelegramMessageService)
	.to(TelegramMessageService);
appContainer.bind<App>(TYPES.Application).to(App);
const app = appContainer.get<App>(TYPES.Application);
app.init();

export { app, appContainer };
