name: tracker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tracker
    env:
      DATABASE_URL: postgresql://root:root@postgres:5432/tracker-assistant?schema=public
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run build
      # run the migration in the test database
      - run: npm run db:push
      - run: npm run start
      - uses: actions/checkout@master

        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          compose-file: './docker/docker-compose.yml'
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/evsaburov/tracker-assistant
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'develop'
