name: tracker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tracker
    steps:
      - uses: actions/checkout@v3
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: docker.pkg.github.com/evsserv/tracker-assistant/tracker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: docker.pkg.github.com
          tags: 'develop'
