name: tracker
on:
  push:
    branches: [master]
    paths:
      - './prisma/**/*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tracker
    steps:
      - uses: actions/checkout@master
      - name: Publish to registy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/evsaburov/tracker-assistant
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'develop'
