name: tracker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tracker
    steps:
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          compose-file: './docker/docker-compose.yml'
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/evsaburov/tracker-assistant
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'develop'
