name: tracker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tracker
    steps:
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/evsaburov/tracker-assistant
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'develop'
